# Generated by Django 5.0.4 on 2024-05-13 06:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_addcar_cars_image'),
        ('users', '0003_address_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cars.addcar', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
