# Generated by Django 5.0.4 on 2024-05-16 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='no',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
