# Generated by Django 5.0.4 on 2024-05-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='orderid',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='statuses',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transid',
            new_name='trans',
        ),
    ]
