# Generated by Django 5.0.4 on 2024-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_orderid_transaction_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_name',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
