# Generated by Django 5.0.4 on 2024-05-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_transaction_address_transaction_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_name',
        ),
    ]
