# Generated by Django 5.0.4 on 2024-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_transaction_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default='abc', max_length=100),
        ),
    ]
