# Generated by Django 5.0.4 on 2024-05-01 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_code', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100)])),
                ('cars_person_name', models.CharField(default='ABC', max_length=100)),
                ('cars_name', models.CharField(max_length=100)),
                ('cars_model', models.CharField(max_length=100)),
                ('cars_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cars_desc', models.TextField()),
                ('cars_image', models.TextField(default='ABC')),
            ],
        ),
    ]
