# Generated by Django 5.0.4 on 2024-05-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_addcar_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='cars_image',
            field=models.TextField(default='ABC'),
        ),
    ]
