# Generated by Django 5.0.4 on 2024-05-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_addcar_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='cars_image',
            field=models.ImageField(default='cars_image.jpg', upload_to='cars_image'),
        ),
    ]
