# Generated by Django 5.0.4 on 2024-05-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_contact'),
        ('cars', '0005_contacts'),
    ]

    operations = [
    ]
